### ISSUE TITLE
Projects with no `affiliate` label show as organization projects

### ISSUE THREAD

**Issue by valencik** [typelevel/typelevel.github.com#420]
Consider cats-time

```yaml
- title: "Cats-Time"
  description: "Instances for Cats Typeclasses for Java 8 Time"
  github: "https://github.com/ChristopherDavenport/cats-time"
```
<img width="373" alt="Screen Shot 2023-02-06 at 4 11 38 PM" src="https://user-images.githubusercontent.com/5440389/217089025-d8ccabd8-29a4-443a-adf1-01a198904c4a.png">
